/*
 * Resend
 * Resend is the email platform for developers.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateDomainOptions
 */
public class UpdateDomainOptionsTest {
    private final UpdateDomainOptions model = new UpdateDomainOptions();

    /**
     * Model tests for UpdateDomainOptions
     */
    @Test
    public void testUpdateDomainOptions() {
        // TODO: test UpdateDomainOptions
    }

    /**
     * Test the property 'clickTracking'
     */
    @Test
    public void clickTrackingTest() {
        // TODO: test clickTracking
    }

    /**
     * Test the property 'openTracking'
     */
    @Test
    public void openTrackingTest() {
        // TODO: test openTracking
    }

}
