/*
 * Resend
 * Resend is the email platform for developers.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CreateApiKeyRequest;
import com.konfigthis.client.model.CreateApiKeyResponse;
import com.konfigthis.client.model.ListApiKeysResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiKeysApi
 */
@Disabled
public class ApiKeysApiTest {

    private static ApiKeysApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ApiKeysApi(apiClient);
    }

    /**
     * Create a new API key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createNewKeyTest() throws ApiException {
        String name = null;
        String permission = null;
        String domainId = null;
        CreateApiKeyResponse response = api.createNewKey(name)
                .permission(permission)
                .domainId(domainId)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve a list of API keys
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListTest() throws ApiException {
        ListApiKeysResponse response = api.getList()
                .execute();
        // TODO: test validations
    }

    /**
     * Remove an existing API key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeExistingKeyTest() throws ApiException {
        String apiKeyId = null;
        api.removeExistingKey(apiKeyId)
                .execute();
        // TODO: test validations
    }

}
