/*
 * Resend
 * Resend is the email platform for developers.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Attachment;
import com.konfigthis.client.model.CreateBatchEmailsResponse;
import com.konfigthis.client.model.Email;
import com.konfigthis.client.model.SendEmailRequest;
import com.konfigthis.client.model.SendEmailResponse;
import com.konfigthis.client.model.Tag;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmailsApi
 */
@Disabled
public class EmailsApiTest {

    private static EmailsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new EmailsApi(apiClient);
    }

    /**
     * Retrieve a single email
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSingleEmailTest() throws ApiException {
        String emailId = null;
        Email response = api.getSingleEmail(emailId)
                .execute();
        // TODO: test validations
    }

    /**
     * Send an email
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendEmailTest() throws ApiException {
        String from = null;
        List<String> to = null;
        String subject = null;
        List<Tag> tags = null;
        String bcc = null;
        String cc = null;
        String replyTo = null;
        String html = null;
        String text = null;
        Object headers = null;
        List<Attachment> attachments = null;
        SendEmailResponse response = api.sendEmail(from, to, subject)
                .tags(tags)
                .bcc(bcc)
                .cc(cc)
                .replyTo(replyTo)
                .html(html)
                .text(text)
                .headers(headers)
                .attachments(attachments)
                .execute();
        // TODO: test validations
    }

    /**
     * Trigger up to 100 batch emails at once.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void triggerBatchEmailsTest() throws ApiException {
        CreateBatchEmailsResponse response = api.triggerBatchEmails()
                .execute();
        // TODO: test validations
    }

}
